name = "hanguleam"
version = "1.0.0"

description = "A Gleam library for Korean text processing, providing comprehensive tools for handling Hangul characters"
licences = ["Apache-2.0"]
repository = { type = "github", user = "jcha0713", repo = "https://github.com/jcha0713/hanguleam" }

internal_modules = [
  "hanguleam/internal/*",
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
glychee = ">= 1.1.2 and < 2.0.0"
startest = ">= 0.7.0 and < 1.0.0"
