// Main test file that imports all assemble module tests
// Individual function tests are organized in separate files:
//
// - combine_vowels_test.gleam
// - combine_character_test.gleam  
// - combine_character_unsafe_test.gleam
// - assemble_function_test.gleam

import hanguleam/core/assemble_function_test
import hanguleam/core/combine_character_test
import hanguleam/core/combine_character_unsafe_test
import hanguleam/core/combine_vowels_test

// Re-export tests for discovery by test runner
pub const combine_vowels_valid_combinations_test = combine_vowels_test.valid_combinations_test

pub const combine_vowels_invalid_combinations_test = combine_vowels_test.invalid_combinations_test

pub const combine_vowels_single_vowels_test = combine_vowels_test.single_vowels_test

pub const combine_character_valid_test = combine_character_test.combine_character_valid_test

pub const combine_character_invalid_choseong_test = combine_character_test.combine_character_invalid_choseong_test

pub const combine_character_invalid_jungseong_test = combine_character_test.combine_character_invalid_jungseong_test

pub const combine_character_invalid_jongseong_test = combine_character_test.combine_character_invalid_jongseong_test

pub const combine_character_first_characters_test = combine_character_test.combine_character_first_characters_test

pub const combine_character_last_characters_test = combine_character_test.combine_character_last_characters_test

pub const combine_character_complex_vowel_empty_jongseong_test = combine_character_test.combine_character_complex_vowel_empty_jongseong_test

pub const combine_character_complex_test = combine_character_test.combine_character_complex_test

pub const combine_character_unsafe_valid_test = combine_character_unsafe_test.combine_character_unsafe_valid_test

pub const assemble_basic_test = assemble_function_test.assemble_basic_test

pub const assemble_single_character_test = assemble_function_test.assemble_single_character_test

pub const assemble_empty_test = assemble_function_test.assemble_empty_test
